# Travis CI setup for CoMeTFoam

sudo: required
dist: trusty
language: cpp

branches:
    only:
        - master
  
notifications:
  email: false

env:
    - OF_VERS=5
    #- OF_VERS=4

before_install:
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam${OF_VERS}

install:
    - source /opt/openfoam${OF_VERS}/etc/bashrc
    - cd src
    - wmake
    - cd ..

before_script:
    - source /opt/openfoam${OF_VERS}/etc/bashrc

script:
    - ./tests/Alltest